### ISSUE TITLE
User survey: What do you use now that this extension is discontinued?

### ISSUE THREAD

**Issue by SRGOM** [Noitidart/Chrome-Store-Foxified#125]
I want to know what people are using to install chrome extensions into firefox

**Comment by piratesephiroth** [comment]
I think the only way is to load them temporarily with about:debugging

**Comment by filips123** [comment]
You can use some workaround as described in README.

**Comment by SRGOM** [comment]
Closing after a wonderful answer here: https://github.com/Noitidart/Chrome-Store-Foxified/issues/122#issuecomment-493442310

**Comment by Noitidart** [comment]
Thanks for asking this question, I really appreciate that community behind this!

**Comment by cherryswiftie13** [comment]
i'm heartbroken this extension was discontinued 😢
