### ISSUE TITLE
Potential solution for communicating with AMO

### ISSUE THREAD

**Issue by stevennyman** [Noitidart/Chrome-Store-Foxified#126]
One potential solution for the CORS problem (#113, #107, #117, #122, etc.) might be to inject a content script onto any AMO page running in an invisible iframe with a specific URL such as https://addons.mozilla.org/en-US/firefox/null/ with `"run_at": "document_start"` and `"all_frames": true`. Then, `fetch` requests would be run from that page, and their results would be returned by monitoring the `webRequest` API for responses. (An example of the `webrequest` API can be found at https://github.com/mdn/webextensions-examples/tree/master/http-response.) Otherwise, response objects could be transferred via content script to background script communication methods such as messaging. Code can be injected to run as if it was on the page by including the following in the content script: 
```js
const script = document.createElement('script');
script.textContent = `[JavaScript to inject]`;
document.documentElement.appendChild(script);
script.remove();
```
(partially borrowed from https://stackoverflow.com/questions/55270830/intercepted-xhr-run-function-before-raising-load)

This should theoretically fix te extension without anyone having to invest in hosting servers and the like.

I'm not sure if I will have the time to implement something like this, so @Noitidart or someone else might want to look into it.

**Comment by stoically** [comment]
Firefox doesn't allow content scripts on restricted domains (such as AMO), so this won't work.

**Comment by Noitidart** [comment]
Thanks for brainstorming this! I missed this!

**Comment by Noitidart** [comment]
The solution by @stoically here seems the way to go - https://github.com/Noitidart/Chrome-Store-Foxified/issues/122#issuecomment-468782495

**Comment by Noitidart** [comment]
@stoically is there an issue with the domain fronter and having cookies?

**Comment by stoically** [comment]
@Noitidart Not sure, never used domain fronting myself, but looking at the CRXViewer code it seems that only specific request headers are modified, which should leave cookie headers intact.

**Comment by stevennyman** [comment]
I'm glad to see this extension gaining forward momentum again! :)

**Comment by Noitidart** [comment]
It's all thanks to the community!
