### ISSUE TITLE
Which file has the code for fetching the Chrome Extension CRX?

### ISSUE THREAD

**Issue by slendertech** [Noitidart/Chrome-Store-Foxified#163]
As @Noitidart may know, I'm trying to get Chrome Store Foxified to get the extension .crx file properly again. I forked this project, but am an amateur with JS. I have working code to get the crx file from the chrome web store, but I'm really not sure where to put it and delete the old code. The code goes as follows:

```
var ExtName;

function GetCRX() {
    chrome.tabs.query({active: true, currentWindow: true}, function(Tabs) {
        ExtName = (Tabs[0].title.split(" - Chrome Web Store")[0]).replace(/[&\/\\:"*<>|?]/g, '');
        var ExtID = Tabs[0].url.split("/")[6].split('?')[0];
        var P1 = "https://clients2.google.com/service/update2/crx?response=redirect&nacl_arch=";
        var P2 = "&prodversion="+navigator.userAgent.split("Chrome/")[1].split(" ")[0]+"&acceptformat=crx2,crx3&x=id%3D"+ExtID+"%26installsource%3Dondemand%26uc";
                
        chrome.runtime.getPlatformInfo(function(PlatformInfo){
            chrome.downloads.download({
                url: P1 + PlatformInfo.nacl_arch + P2,
                saveAs: true
            });
        });
    });
}

```

Thanks in advance for any help given!
Slender Tech

**Comment by Noitidart** [comment]
Thanks for driving this! Would love help from the community. You all are so great!

**Comment by slendertech** [comment]
> Thanks for driving this! Would love help from the community. You all are so great!

What I was asking is what file has the code for fetching data from the chrome web store?

**Comment by Noitidart** [comment]
Oh I get you now, sorry about that. The fetching is happening here - https://github.com/Noitidart/Chrome-Store-Foxified/blob/master/src/webext/flow-control/extensions/index.js#L137

**Comment by slendertech** [comment]
> Oh I get you now, sorry about that. The fetching is happening here

Thank you very much!
