### ISSUE TITLE
Signing always fails with "Error decoding signature."

### ISSUE THREAD

**Issue by Zaggy1024** [Noitidart/Chrome-Store-Foxified#20]
Lately I've been getting this error for every extension I try to install.

`{
    "msg": "signing-failed: submit failed",
    "xhr": {
        "status": 401,
        "response": {
            "detail": "Error decoding signature."
        }
    }
}`

Any idea what's wrong?

Edit: Forgot to mention, I'm on 32-bit Nightly 48.0 on Windows 10.

**Comment by Noitidart** [comment]
This was an issue with the browserified jsonwebtoken module. In nightly, it's up to the latest es6 standards, so something in the browserification/transpiling of the module was incompatible. I wrote my own jwt generator for v1.10 and just uploaded it. I couldn't figure out the actual thing that changed so this took awhile to fix, but fixed now :)
