### ISSUE TITLE
Temporarily rejected from addons.mozilla.org

### ISSUE THREAD

**Issue by Noitidart** [Noitidart/Chrome-Store-Foxified#21]
The latest version, v1.7, was rejected from addons.mozilla.org - I will rework it to their specifications and update soon.

**Comment by Noitidart** [comment]
Fixed in v1.8 - awaiting approval - https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/?src=github

**Comment by Juesto** [comment]
Apparently we're a "special" case :)

**Comment by Noitidart** [comment]
v1.11 preliminarily approved - closing issue
