### ISSUE TITLE
Not working in latest Nightly

### ISSUE THREAD

**Issue by newsjunkie247** [Noitidart/Chrome-Store-Foxified#22]
Doesn't seem to work in latest Nightly 49 and an addon that works in 46 has simply disappeared in 49.

**Comment by Noitidart** [comment]
The submissions since v1.7 got rejected multiple times. I just uploaded v1.11 for preliminary review two days ago. As soon as that get's approved, it will get signed, and then you should be able to use it. Excuse the chaos, I had to better adhere to some AMO policies, that was the reason or rejection.

**Comment by newsjunkie247** [comment]
actually it does work on the page with the newest version, but the app doesn't install: https://chrome.google.com/webstore/detail/buzzsumo/gedpbnanjmblcmlfhgfficjnglidndfo even though it works in 46, but I don't know if that has to do with the app or the extension.

**Comment by newsjunkie247** [comment]
It's just stuck on installing in 49, but the signing and everything works in 46.

**Comment by Noitidart** [comment]
Can you please try restarting your browser. 

Did you try clicking "Install as temporary addon"? It might be that the file is locked.

**Comment by newsjunkie247** [comment]
It seems to be something else, the temporary install simply fails and the regular one it just gets stuck on installing even in a different profile (though the signing seems to work). Even tried deleting the files, didn't help. Works fine in 46 :-(

**Comment by Noitidart** [comment]
Thanks very much for the detailed testing. I'll take a look at this.

**Comment by Noitidart** [comment]
This was fixed.
