### ISSUE TITLE
Can't launch "Chrome app" extensions such as Signal

### ISSUE THREAD

**Issue by kalentia** [Noitidart/Chrome-Store-Foxified#23]
I can install Signal just fine, but there is no way to open it either from the settings or the apps launcher. I assume this would be true of other Chrome app extensions.

**Comment by Noitidart** [comment]
Hi Kalentia, this is correct. Apps are not supported by the WebExtensiosn API so it won't work with Foxified. In the next version I'll not enable the app buttons for foxified.
