### ISSUE TITLE
Not working with Google Cast extension

### ISSUE THREAD

**Issue by NessunoIM** [Noitidart/Chrome-Store-Foxified#24]
Hi, first of all congrats for your work. 

I tried to install Google Cast (chrome extension), installation works fine but extension doesn't work. When I click on icon extension, doesn't appear any pop-up.

![ddj](https://cloud.githubusercontent.com/assets/19640640/15682711/4997cd38-275f-11e6-8806-39a206c8dd36.png)

Google extension link: https://chrome.google.com/webstore/detail/google-cast/boadgeojelhgndaghljhdicfkmllpafd?utm_source=chrome-app-launcher-info-dialog

**Comment by Noitidart** [comment]
Hi there @NessunoIM  - you are correct this extension does not work yet. The WebExtension API (which powers Google Chrome extensions) is not yet completed. The Firefox team is still working on it and should have complete parity in the near future. :)

**Comment by Juesto** [comment]
These are one of the complex extensions that are unlikely to be supported via WebExt, the addon only enables installing extensions from Chrome web store, extensions themselves depend on WebExt not us.
