### ISSUE TITLE
Too many install buttons!

### ISSUE THREAD

**Issue by fritzophrenic** [Noitidart/Chrome-Store-Foxified#30]
It is confusing which button or link to select to install an extension. There is an "Install Temporarily" link and also a "Temporarily Install Unsigned Addon" button, which I think might do the same thing. There is a "Sign Addon then Install" link which I assume is the same as the "Sign Addon" button, but maybe there is a difference.

The purpose of "Just Sign and Download" vs. "Save CRX to File" vs. "Save Unsigned Addon to File" is also not clear, nor is the reason a normal user would want to use those.
![drive_install_dialog](https://cloud.githubusercontent.com/assets/1334420/16953458/bc6265ae-4d92-11e6-8c19-2ce76bf46839.png)

**Comment by Noitidart** [comment]
Totally agreed. Those buttons at the bottom are for in case user does some combination that ends them up on a blank message page. It's a backup, I should maybe hide that till user clicks it. I'll hide it as "Show Advanced Controls" maybe.

**Comment by Juesto** [comment]
remember its a tool intended for advanced users
its okay how it is, perhaps too much
+1

**Comment by Noitidart** [comment]
Cool points @Juesto thanks! I need to prettify these buttons too, they are downright ugly!

**Comment by Noitidart** [comment]
Removed all of them in v3 - https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/
