### ISSUE TITLE
Can't access preferences

### ISSUE THREAD

**Issue by Yaestro** [Noitidart/Chrome-Store-Foxified#37]
I need to access the extension's preferences in order to make it work.

Extension: **CR HLS Player**
https://chrome.google.com/webstore/detail/cr-hls-player/aeajdeepnjjdekpbicjhfldagkjndjid

**Comment by Noitidart** [comment]
This extension does not work yet. I installed it an I see this in error console:

> TypeError: chrome.runtime.onInstalled is undefined[Learn More]bgp.js:1:1

This means that WebExtension API does not yet support `chrome.runtime.onInstalled`. We see this is in the docs here - https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities#runtime

As soon as WebExtensions API gets this support then this addon will work. :)

**Comment by Yaestro** [comment]
Ah. Got it.

Thanks!

**Comment by Noitidart** [comment]
My pleasure, if you have any more questions just post it up here we'll help you out. :)
