### ISSUE TITLE
Error: Your JSON file could not be parsed

### ISSUE THREAD

**Issue by neomodern** [Noitidart/Chrome-Store-Foxified#47]
This is for the extension [The Great Suspender](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg) and this is the error message I get: http://i.imgur.com/QxcjOzt.png

**Comment by Noitidart** [comment]
Thanks for sharing @neomodern  - it seems the manifest.json of this extension is not proper json. I will see if the folks at Mozilla are willing to accomadate for bad JSON.

**Comment by neomodern** [comment]
What did they say?

**Comment by Noitidart** [comment]
@neomodern They said it's an app and they don't support that yet. So if you want to use it we would have to dive into it and tweak it to work as an extension.

**Comment by Noitidart** [comment]
Oh whoops this is a different isue I think, let me check  with webext team again.

**Comment by Noitidart** [comment]
Note to self

This is the json of latest great suspender:

```
{
    "update_url": "https://clients2.google.com/service/update2/crx",
    "name": "The Great Suspender",
    "description": "Automatically suspends unused tabs to free up system resources",
    "version": "6.21",
    "permissions": ["tabs", "storage", "history", "unlimitedStorage", "http://*/*", "https://*/*", "chrome://favicon/*", "http://greatsuspender.github.io/", "contextMenus"],
    "background": {
        "scripts": ["js/db.js", "js/gsUtils.js", "js/background.js"],
        "persistent": true
    },
    "content_scripts": [{
        "matches": ["http://*/*", "https://*/*"],
        "js": ["js/contentscript.js"]
    }],
    "browser_action": {
        "default_title": "The Great Suspender",
        "default_icon": "img/icon19.png",
        "default_popup": "popup.html"
    },
    "options_page": "options.html",
    "icons": {
        "16": "img/icon16.png",
        "48": "img/icon48.png",
        "128": "img/icon128.png"
    },
    "web_accessible_resources": ["suspended.html", "history.html", "clean.html", "css/style.css", "css/suspended.css"],
    "content_security_policy": "script-src 'self' https://ssl.google-analytics.com; object-src 'self'",
    "incognito": "split",
    "manifest_version": 2,
    "minimum_chrome_version": "24",
    "commands": {
        "1-suspend-tab": {
            "description": "Suspend active tab",
            "suggested_key": {
                "default": "Ctrl+Shift+S"
            }
        },
        "2-unsuspend-tab": {
            "description": "Unsuspend active tab",
            "suggested_key": {
                "default": "Ctrl+Shift+U"
            }
        },
        "3-suspend-active-window": {
            "description": "Suspend all tabs in active window"
        },
        "4-unsuspend-active-window": {
            "description": "Unsuspend all tabs in active window"
        },
        "5-suspend-all-windows": {
            "description": "Suspend all tabs in all windows"
        },
        "6-unsuspend-all-windows": {
            "description": "Unsuspend all tabs in all windows"
        }
    },
    "applications": {
        "gecko": {
            "id": "klbibkeccnjlkjkiokjodocebajanakg@chrome-store-foxified-unsigned"
        }
    }
}
```

**Comment by Noitidart** [comment]
Note to self

This is the response when it has failed - i can use this to quit the retry attempts and state validation failed:
```
{
active:false,
automated_signing:true,
files:Array[0],
guid:"klbibkeccnjlkjkiokjodocebajanakg@chrome-store-foxified-3046110587"
passed_review:false
pk:"e272ee909b6a48ea82dabca318667fbe"
processed:true
reviewed:false
url:"https://addons.mozilla.org/api/v3/addons/klbibkeccnjlkjkiokjodocebajanakg@chrome-store-foxified-3046110587/versions/6.21/uploads/e272ee909b6a48ea82dabca318667fbe/"
valid:false
validation_results: {
compatibility_summary:{
errors:0,
notices:0,
warnings:0
},
detected_type:"extension",
ending_tier:5,
errors:1,
is_upgrade_to_webextension:true,
messages:Array[9],
metadata:Object,
notices:1,
passed_auto_validation:true,
signing_summary:{
high:0,
low:0,
medium:0,
trivial:0
},
success:false,
warnings:7,
validation_url:"https://addons.mozilla.org/en-US/developers/upload/e272ee909b6a48ea82dabca318667fbe",
version:"6.21"

}
```

**Comment by Noitidart** [comment]
@neomodern this was a bug in Firefox and it was fixed in v51 - https://bugzilla.mozilla.org/show_bug.cgi?id=1277686

What browser version are you using?

**Comment by Noitidart** [comment]
Apparently they don't have a plan for fixing this right now:

src: https://bugzilla.mozilla.org/show_bug.cgi?id=1280027#c4
>  Andy McKay [:andym] 2016-10-20 11:21:40 PDT
>
> No, it will still reject manifests that do not say "spanning" for incognito mode, as the validation results show. I currently know of no bug on file to loosen that restriction on AMO.

So the only thing we can do is modify the manifest.json of this to go from "split" to "spanning".

**Comment by neomodern** [comment]
I'm using the normal release channel 49.0.1.

Ah so it's a one line fix then? That sounds good. 

I'm not a dev so I'm not sure how to edit the JSON file though and repackage it.

**Comment by Noitidart** [comment]
I attached the XPI with manifest modified here. It wouldn't let me upload xpi so i renamed it to docx. After downloading this, rename it to xpi. I also signed it for you. :)

[the_great_suspender-6.21-an+fx.docx](https://github.com/Noitidart/Chrome-Store-Foxified/files/542805/the_great_suspender-6.21-an.fx.docx)

**Comment by neomodern** [comment]
Thanks! Installed fine without any warning messages, cheers for your help.

The extension itself doesn't seem to work display properly (looks [like this](http://i.imgur.com/cOuyOSa.png) on Chrome but [like this](http://i.imgur.com/kj3rWsd.png) on Firefox) but that's probably due to the current WebExtensions functionality I guess? Either way that's not to do with Foxified so I'll go ahead and close this issue.

**Comment by Noitidart** [comment]
That's interesting, that display issue should be just html in an iframe. That's interesting why its not displaying. It is very likely that webext api's are not fully available for it. If you open "browser console" with ctrl+shift+j it should show some errors. Which coders should be able to fix if they have some time.
