### ISSUE TITLE
Autofill Extension Issue

### ISSUE THREAD

**Issue by Noitidart** [Noitidart/Chrome-Store-Foxified#52]
This is in reply to reveiw here - 

When I try to install it I get this error:
````
1483464493540	addons.webextension.<unknown>	ERROR	Loading extension 'null': Loading locale file _locales/en/messages.json: SyntaxError: JSON.parse: expected property name or '}' at line 3 column 3 of the JSON data  Log.jsm:753
Unknown localization message generaldescription  ExtensionUtils.jsm:490
1483464493546	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
1483464493552	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Error processing permissions.4: Unknown permission "unlimitedStorage"
1483464493553	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Error processing update_url: An unexpected property was found in the WebExtension manifest.
1483464493554	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.
1483464493562	addons.webextension.nlmmgnhgdeffjkdckmikfpnddkbbfkkk@chrome-store-foxified-unsigned	ERROR	Loading extension 'nlmmgnhgdeffjkdckmikfpnddkbbfkkk@chrome-store-foxified-unsigned': Loading locale file _locales/pt_PT/messages.json: SyntaxError: JSON.parse: expected property name or '}' at line 3 column 3 of the JSON data  Log.jsm:753
1483464493563	addons.webextension.nlmmgnhgdeffjkdckmikfpnddkbbfkkk@chrome-store-foxified-unsigned	ERROR	Loading extension 'nlmmgnhgdeffjkdckmikfpnddkbbfkkk@chrome-store-foxified-unsigned': Loading locale file _locales/en/messages.json: SyntaxError: JSON.parse: expected property name or '}' at line 3 column 3 of the JSON data  Log.jsm:753
1483464493564	addons.webextension.nlmmgnhgdeffjkdckmikfpnddkbbfkkk@chrome-store-foxified-unsigned	ERROR	Loading extension 'nlmmgnhgdeffjkdckmikfpnddkbbfkkk@chrome-store-foxified-unsigned': Loading locale file _locales/zh_CN/messages.json: SyntaxError: JSON.parse: expected property name or '}' at line 3 column 3 of the JSON data  Log.js
```

We need to fix the JSON in his messages.json files.

**Comment by Noitidart** [comment]
In the attached, I fixed the messages.json files so it installs now. However he has errors within his addon. Probably unsupported APIs.

[Autofill - Version 7.0.0 - UNSIGNED - LOCALE JSON FIXED.zip](https://github.com/Noitidart/Chrome-Store-Foxified/files/682873/Autofill.-.Version.7.0.0.-.UNSIGNED.-.LOCALE.JSON.FIXED.zip)

**Comment by arun921** [comment]
i need to install
auto fill version 6.8 
i have already sent it 
it worked well in firefox (i mean nighty)
U CAN DOWNLOAD OLDER VERSION 
BELOW LINK
https://drive.google.com/file/d/0B9kUATC-pBJtUTlIQWUxdkVEMHc/view?usp=sharing

**Comment by Noitidart** [comment]
Oh I see! So you want me to convert that crx to xpi? I think you can install crx directly from about:debugging did you try that?

**Comment by arun921** [comment]
no , i need to enable debugging

**Comment by arun921** [comment]
There was an error during installation: Directory C:\Users\kumar\Downloads does not contain a valid install manifest

**Comment by arun921** [comment]
when i was trying to install 
showing above error

**Comment by arun921** [comment]
what i do next

**Comment by Noitidart** [comment]
I converted this addon for you to XPI. I had to upload as zip as github wouldn't allow xpi. Please download this, then rename to .xpi and install from about:debugging it should work.

[autofill-6-8-0-UNSIGNED.zip](https://github.com/Noitidart/Chrome-Store-Foxified/files/682990/autofill-6-8-0-UNSIGNED.zip)

**Comment by arun921** [comment]
thank u

**Comment by arun921** [comment]
this addon could not be installed because it appears to be corrupted

**Comment by arun921** [comment]
showing error
i was trying to install with foxfields it successfully installed

**Comment by Noitidart** [comment]
Yeah I get that corrupt error as well. This is what shows in console:

```
n is undefined  autofill.js:7
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:265
n is undefined  autofill.js:7
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:265
n is undefined  autofill.js:7
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:265
n is undefined  autofill.js:7
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:265
n is undefined  autofill.js:7
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:265
Use of nsIFile in content process is deprecated.  loader.js:278:6
TypeError: this.cloneScope is null ExtensionCommon.jsm:298:1
SyntaxError: JSON.parse: expected double-quoted property name at line 62 column 1 of the JSON data
Stack trace:
readJSON/</<@resource://gre/modules/Extension.jsm:362:19
onStopRequest@resource://gre/modules/NetUtil.jsm:128:17
  controls.js:63:9
```

It means the author has some issues internally he needs to debug and handle specifically for Firefox.

**Comment by arun921** [comment]
ok thank you
can i ask one question

**Comment by Noitidart** [comment]
Yes please ask anything :) thanks

**Comment by arun921** [comment]
can i save web page on desktop with ULR
IF I CLICK ON THAT IT SHOULD OPEN WITH ULR AS I SAVE

**Comment by arun921** [comment]
I NEED TO FILL FORM IN ONLINE VERY QUICKLY 
THATS WHY I AM ASKING 
CAN I SAVE THAT FORM BEFORE

**Comment by Noitidart** [comment]
Yes you can drag a shortcut link to destkop like this I recorded a screencast - https://www.youtube.com/watch?v=cFpJpfJwlKk

**Comment by arun921** [comment]
NOT LIKE THAT 
IT SHOULD OPEN WITH HTML , CSS, AND JS

**Comment by arun921** [comment]
IF IT NOT POSSIBLE

**Comment by Noitidart** [comment]
Oh try it this way -

![](http://i.imgur.com/BO54xvx.png)

**Comment by arun921** [comment]
YES I KNOW THIS 
BUT SHOULD CONNECT TO THE SERVER

**Comment by arun921** [comment]
IT IS SHOWING LOCAL HOST

**Comment by Noitidart** [comment]
I'm not sure :( I'm not too familiar with this kind of stuff. Excuse that please. :(

**Comment by arun921** [comment]
HOW CAN I SEND U  A IMAGE

**Comment by Noitidart** [comment]
You can take screenshots and upload to imgur with this addon -
https://addons.mozilla.org/en-US/firefox/addon/nativeshot/

**Comment by arun921** [comment]
https://drive.google.com/file/d/0B9kUATC-pBJtMW9XV0dRUHUxcGM/view?usp=sharing

**Comment by arun921** [comment]
I NEED TO FILL THAT FORM

**Comment by arun921** [comment]
R U SEEING value in form i need to fill

**Comment by arun921** [comment]
that web site supporting well in firefox
thats the reason i am asking

**Comment by Noitidart** [comment]
Yep I can see the image. I know Mozilla has a project to fill forms but i don't think it's released yet:

* https://mozilla.invisionapp.com/share/AP8TFZ22G
* https://wiki.mozilla.org/Firefox/Features/Form_Autofill

**Comment by arun921** [comment]
can save this form script and inject into website

**Comment by Noitidart** [comment]
I'm not sure. I wish I could help you more. I think best bet is to contact them at IRC or mailing list:

````
 IRC Channel: #formfill
Mailing list: autofill@lists.mozilla.org 
```

**Comment by arun921** [comment]
thank you veeeeeeeeeeeeeeeeeeeeeeeeeerrrrrrrrrrrrrrrrrrrrrryyyyyyyyyyyyy much

**Comment by Noitidart** [comment]
Haha my pleasure I hope you can get the form fill feature from Firefox working. If I hear anything I will let you know. :)

**Comment by arun921** [comment]
ho
i never believe 
you sent add on 
it is working well
thank you 
verry much
i never forget you timely help 
thank you

**Comment by Noitidart** [comment]
Awesome thank you arun921!

**Comment by arun921** [comment]
https://chrome.google.com/webstore/detail/form-editor/klaecimjlbpfompicealiiifcdjnkbpn?hl=en
i need ur help

**Comment by arun921** [comment]
r u there
