### ISSUE TITLE
Port to WebExtension? 

### ISSUE THREAD

**Issue by heubergen** [Noitidart/Chrome-Store-Foxified#63]
Any chance for a port? Can I help or assist you in any way?

**Comment by Noitidart** [comment]
Thank you so much brother for asking!!!

My biggest problem with a port to a webextension is that I am not able to auto-install the extension. Do you have any ideas about this?

I am considering this:
* Save the extension as a blob, then open the blob in a new tab - I am hoping that the browser prompts the user to install the addon like normal
* If that doesn't work I will have to try `chrome.management` but I can't find anything there that will help me.

**Comment by Noitidart** [comment]
Do you have UX/UI experience? In the webextension I plan to open a new tab when you click "add to fiefox". All the downloaded extensions will be cataloged in there. As I no longer have file access, I have to make this an HTML5 app.

If you could design a portal/dashboard that would be awesome!

**Comment by nt1m** [comment]
To be honest, I would be fine if the extension just downloaded the XPI using the downloads API. Then I would only need to drag the xpi from the downloads panel into the browser.

**Comment by Noitidart** [comment]
Port completed and released!

https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/
