### ISSUE TITLE
Convert local CRX file

### ISSUE THREAD

**Issue by voviks21** [Noitidart/Chrome-Store-Foxified#64]
Hello! I enjoy your extension, but its miss very important feature: installation local saved .crx file or even folder with sources. But i packed source to crx with Chrome and now i need port it to Firefox, how can i do it? Can you add file selection option to pick packed locally saved CRX file and convert it? I tried even replace URL of google webstore to local file but seems not work...

**Comment by Noitidart** [comment]
I agree this would be a great feature. I am so busy right now, I haven't been able to work too much on this. :( I will definitely add this though.

**Comment by Noitidart** [comment]
This feature landed in v3, just released it. https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/
