### ISSUE TITLE
The Chrome-Store-Foxified extension is not supported on the Quantum 57 b6 Firefox versions

### ISSUE THREAD

**Issue by serial02** [Noitidart/Chrome-Store-Foxified#70]
The Chrome-Store-Foxified extension is not supported on the Quantum 57 b6 Firefox versions, and the Chrome web store extensions can not be installed.

We would like to know when this extension will be updated to new versions of Firefox 57.

![captura de tela de 2017-10-09 20-01-22](https://user-images.githubusercontent.com/32621790/31362045-ddfcf1c0-ad2c-11e7-80f4-e80e9034113b.png)

Come down already thank you for your attention and we look forward to a return soon.

Serial02

**Comment by Noitidart** [comment]
Thanks for the note @serial02  - we're tracking my progress here - https://github.com/Noitidart/Chrome-Store-Foxified/issues/69
