### ISSUE TITLE
Tutorial problems

### ISSUE THREAD

**Issue by Madis0** [Noitidart/Chrome-Store-Foxified#80]
I figured that posting this as a new issue would be a better way to track changes.
![](http://i.pi.gy/xk2le.png)

(if you see only half of the image, it's GitHub's fault - [direct link here](http://i.pi.gy/xk2le.png))

1. Text misaligned compared to thumbnails
2. "extensions"
3. Space after comma
4. Wrong name (for now?)
5. Unnecessary periods

**Comment by Noitidart** [comment]
Thanks very much @Madis0 for such a detailed analysis!

Pinging @QWERTYUIOPYOZO  - I basically blindly copied and pasted haha as I didn't feel it would be nice to change your hard work. I only made a change to pure CSS so it plays well with react copy-pasting. If possible could you please make the changes using the Developer Tools in browser, and then share the updated CSS. :)

No rush :)

**Comment by QWERTYUIOPYOZO** [comment]
Hi, Sorry about this.
When developing this I did not realise that you were developing the UX with react.
Would you like me to redo this in React?

**Comment by Noitidart** [comment]
If possible yes please! :) Also unsigned addon tutorial needs help please haha - https://github.com/Noitidart/Chrome-Store-Foxified/issues/86

I did make the weclome one pure CSS, so you can just open up the page and use the devtools to modify the CSS and send that my way :)

No rush please I know time is valuble and hard to come by.

**Comment by QWERTYUIOPYOZO** [comment]
Pull requests are ready to merge.

**Comment by Noitidart** [comment]
Released in v3.3
