### ISSUE TITLE
Settings counter

### ISSUE THREAD

**Issue by Madis0** [Noitidart/Chrome-Store-Foxified#82]
What is the purpose of the counter in the settings? Does it do anything for the user? If not, I would suggest removing it from the release version, keeping it only in the betas if necessary.

**Comment by Noitidart** [comment]
I forgot it in shoot haha. Removed it in 3.1. Thanks for these topics! :) I appreciate the interaction a lot!

**Comment by Noitidart** [comment]
fixed in 3.2
