### ISSUE TITLE
Remove from dashboard

### ISSUE THREAD

**Issue by Madis0** [Noitidart/Chrome-Store-Foxified#84]
A button or link would be nice to remove an extension from the CSF dashboard.

**Comment by Noitidart** [comment]
I totally forgot about this, i added it to 3.1 hope to release tonight. :)

**Comment by Noitidart** [comment]
Released in 3.2 which just went live

**Comment by PAVAN9497** [comment]
Not able to add price tracker extension in Firefox plss fix it as soon as possible

**Comment by Noitidart** [comment]
@PAVAN9497 I don't have control over the extensions. I only can control Chrome Store Foxified extension. If that extension doesn't work, it needs to be tweaked by the community. I created a forum, if you post about it, hopefully others with time will join in and share their tweaks.

**Comment by Noitidart** [comment]
I tried installing your price tracker extensions as an unsigned extesnion and it worked:

![](https://screenshots.firefoxusercontent.com/images/a13f8c80-508d-4718-8f99-0bafa8ccc4a9.png)
