### ISSUE TITLE
Could not extract generated credentials...

### ISSUE THREAD

**Issue by berlihingen** [Noitidart/Chrome-Store-Foxified#89]
...and then: "please report this bug", so I do.
Extension: https://chrome.google.com/webstore/detail/ezlinkpreview/nnkcfbiefgdaceeplickkkmifpicbpcc
Works nice in Opera, while written for Chrome. 'Install', 'retry', 'upload' - nothing helped.

**Comment by Noitidart** [comment]
Thanks very much for the report. I will try to fix this up. I didn't expect this error to happen. Another also got this error just recently. I will try to reproduce this.

**Comment by QWERTYUIOPYOZO** [comment]
I get the same error, but since I use dev edition, I just install them unsigned.

**Comment by Noitidart** [comment]
Reproduced the bug, fixed, uploaded fix in v3.3 to AMO.

Thanks all for the report!
