### ISSUE TITLE
Parse URL properly

### ISSUE THREAD

**Issue by Noitidart** [Noitidart/Chrome-Store-Foxified#9]
If you try to download from this page it fails: https://chrome.google.com/webstore/detail/tms-torrent-search-extens/ngcldkkokhibdmeamidppdknbhegmhdh?utm_source=chrome-app-launcher-info-dialog

It works from this page though: https://chrome.google.com/webstore/detail/tms-torrent-search-extens/ngcldkkokhibdmeamidppdknbhegmhdh

In the above case it thinks the id is:

```
in actOnExt server side, aExtId: ngcldkkokhibdmeamidppdknbhegmhdh?utm_source=chrome-app-launcher-info-dialog aExtName: TMS - Torrent search, extension bootstrap.js:157
```

**Comment by Juesto** [comment]
Weird, it shouldnt take that in account.
