### ISSUE TITLE
Parsing Hangs

### ISSUE THREAD

**Issue by 3v1n0** [Noitidart/Chrome-Store-Foxified#98]
Hi, I've been quite a lot of extensions (about 35) already in my quantum firefox, but this one seems to use more than the half memory of them all. Here's what my `about:memory` shows:

![immagine](https://user-images.githubusercontent.com/345675/32933448-2c29dea2-cb38-11e7-9e99-15d4997cc547.png)

I've just three chrome extensions listed there.

**Comment by 3v1n0** [comment]
Ah, never mind... I think that's caused by the extensions that are being installed (and that for some reason stopped)

![immagine](https://user-images.githubusercontent.com/345675/32933728-a72a8296-cb38-11e7-8977-7ed252368482.png)

**Comment by Noitidart** [comment]
Thanks for the in depth look here! 

I

**Comment by 3v1n0** [comment]
No worries, however this triggers another issue, as as you can see the [ImTranslator](https://chrome.google.com/webstore/detail/noaijdpnepcgjemiklgfkcfbkokogabh) extension doesn't get properly parsed... And the process hangs on parsing. So I can't neither add or remove this app, and the memory consumption stays.

**Comment by Noitidart** [comment]
I'll test out ImTranslator to see why it's hanging :)

**Comment by seoh** [comment]
Could you test [Tooltip Dictionary](https://chrome.google.com/webstore/detail/tooltip-dictionary-englis/hcidimjcobcnahiceedndikkenbibpop) too? I have a same problem.

**Comment by Noitidart** [comment]
Got it @seoh will do. The more addon names that causes that better so I can hopefully reproduce it with at least one.

**Comment by 3v1n0** [comment]
So, the fixed version should have landed, however how can I now try to redownload one of such extension? As, ImTranslator, for example, is stuck in my view in "parsing" and if I try to add it newly the extension complains "You have previously already downloaded this extension".

So, I've no way to delete the broken one, nor to redownload it properly...

**Comment by Noitidart** [comment]
@3v1n0 click on "Cancel" it should delete it out. If that causes errors, go to "Settings" page and click on "Clear Memory" then disable then enable the extension.

**Comment by 3v1n0** [comment]
Thanks, that worked.

**Comment by Noitidart** [comment]
Thanks for bearing with me. I actually didn't do a proper release and didn't implement error handling. I need to do that soon.

**Comment by soredake** [comment]
@Noitidart parsing this extension still fails https://chrome.google.com/webstore/detail/etsy-searchton/honjddkcdoamlhphbffgcaadcnfchjjo
