### ISSUE TITLE
Ugoira2GIF Parsing Hangs

### ISSUE THREAD

**Issue by MindlessCirno** [Noitidart/Chrome-Store-Foxified#99]
Link: https://chrome.google.com/webstore/detail/ugoira2gif/ionmgpeclkmpjkmfejilaihdegkjehfj
Don't know what I should to do

**Comment by Noitidart** [comment]
fixed in 3.4 thanks for this report!

**Comment by Noitidart** [comment]
closed here https://github.com/Noitidart/Chrome-Store-Foxified/commit/bd232c37fe2f2575b78f8e5875eeb2cfa2924105
